/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIPlanInput {
  'age' : bigint,
  'painScore' : bigint,
  'primaryComplaint' : string,
  'domain' : string,
  'patientGoals' : string,
  'functionalLimitations' : string,
  'medicalHistory' : string,
  'gender' : string,
  'bodyPart' : string,
  'symptomDuration' : string,
}
export interface AIPlanOutput {
  'keyImpairments' : string,
  'sessionDuration' : string,
  'functionalProblems' : string,
  'redFlagReferral' : string,
  'contraindications' : string,
  'exerciseList' : Array<string>,
  'disclaimer' : string,
  'longTermGoals' : string,
  'frequency' : string,
  'shortTermGoals' : string,
  'precautions' : Array<string>,
}
export interface Assessment {
  'id' : AssessmentId,
  'clinicalScales' : Array<ClinicalScale>,
  'dateCreated' : bigint,
  'patientId' : PatientId,
  'clinicianId' : ClinicianId,
  'redFlags' : Array<string>,
  'subjectiveHistory' : SubjectiveHistory,
  'objectiveTest' : ObjectiveTest,
}
export type AssessmentId = string;
export interface ClinicalScale {
  'responses' : Array<bigint>,
  'name' : string,
  'score' : bigint,
  'hjiquestions' : string,
  'interpretation' : string,
}
export type ClinicianId = Principal;
export interface Deviation {
  'name' : string,
  'description' : string,
  'severity' : bigint,
}
export type ExternalBlob = Uint8Array;
export type ImpressionId = string;
export interface ObjectiveTest {
  'muscleTesting' : string,
  'rangeOfMotion' : string,
  'gaitAssessment' : string,
  'balanceAssessment' : string,
  'neurologicalScreening' : string,
  'cardiopulmonaryScreening' : string,
}
export type PatientId = string;
export interface PatientProfile {
  'id' : PatientId,
  'contactInfo' : string,
  'activityGoals' : string,
  'dateOfBirth' : string,
  'medicalHistory' : string,
  'gender' : string,
  'lastName' : string,
  'surgicalHistory' : string,
  'firstName' : string,
}
export interface PostureAssessmentInput {
  'landmarks' : Array<[string, string]>,
  'viewType' : string,
  'alignmentData' : Array<[string, string]>,
}
export interface PostureAssessmentReport {
  'correctiveFocusAreas' : Array<string>,
  'deviations' : Array<Deviation>,
  'effectsOnMovement' : Array<string>,
  'disclaimer' : string,
  'patientFriendlySummary' : string,
  'explanations' : Array<string>,
}
export interface ProvisionalPhysioImpression {
  'id' : ImpressionId,
  'observedDeviations' : Array<string>,
  'dateCreated' : bigint,
  'generatedImpression' : string,
  'functionalDifficulties' : Array<string>,
}
export interface SubjectiveHistory {
  'aggravatingFactors' : string,
  'functionalLimitations' : string,
  'relievingFactors' : string,
  'onsetHistory' : string,
  'chiefComplaint' : string,
}
export interface TreatmentPlan {
  'id' : string,
  'dateCreated' : bigint,
  'patientId' : PatientId,
  'recommendations' : Array<string>,
  'impairments' : string,
  'clinicianId' : ClinicianId,
  'functionalLimitations' : string,
  'diagnosis' : string,
  'goals' : string,
  'interventions' : Array<string>,
}
export interface UserEntry {
  'principal' : Principal,
  'role' : UserRole,
  'profile' : [] | [UserProfile],
}
export interface UserProfile {
  'name' : string,
  'credentials' : string,
  'specialization' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAssessment' : ActorMethod<[Assessment], AssessmentId>,
  'addPatient' : ActorMethod<[PatientProfile], undefined>,
  'addTreatmentPlan' : ActorMethod<[TreatmentPlan], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateClinicalScaleScore' : ActorMethod<
    [string, Array<bigint>],
    ClinicalScale
  >,
  'generateAIPlan' : ActorMethod<[AIPlanInput], AIPlanOutput>,
  'generateProvisionalPhysioImpression' : ActorMethod<
    [PatientId, Array<string>, Array<string>],
    ProvisionalPhysioImpression
  >,
  'getAllPatients' : ActorMethod<[], Array<PatientProfile>>,
  'getAllProvisionalImpressions' : ActorMethod<
    [],
    Array<ProvisionalPhysioImpression>
  >,
  'getAllUsers' : ActorMethod<[], Array<UserEntry>>,
  'getAssessment' : ActorMethod<[AssessmentId], [] | [Assessment]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClinicianDashboard' : ActorMethod<
    [],
    {
      'aiPlanCount' : bigint,
      'treatmentPlanCount' : bigint,
      'patientCount' : bigint,
      'assessmentCount' : bigint,
    }
  >,
  'getPatient' : ActorMethod<[PatientId], [] | [PatientProfile]>,
  'getPatientAssessments' : ActorMethod<[PatientId], Array<Assessment>>,
  'getPatientTreatmentPlans' : ActorMethod<[PatientId], Array<TreatmentPlan>>,
  'getProvisionalImpressions' : ActorMethod<
    [PatientId],
    Array<ProvisionalPhysioImpression>
  >,
  'getTreatmentPlan' : ActorMethod<[string], [] | [TreatmentPlan]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'processPostureImage' : ActorMethod<[ExternalBlob], PostureAssessmentReport>,
  'removeUser' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitPostureAssessment' : ActorMethod<
    [PostureAssessmentInput],
    PostureAssessmentReport
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];