/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AssessmentId = IDL.Text;
export const ClinicalScale = IDL.Record({
  'responses' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'score' : IDL.Nat,
  'hjiquestions' : IDL.Text,
  'interpretation' : IDL.Text,
});
export const PatientId = IDL.Text;
export const ClinicianId = IDL.Principal;
export const SubjectiveHistory = IDL.Record({
  'aggravatingFactors' : IDL.Text,
  'functionalLimitations' : IDL.Text,
  'relievingFactors' : IDL.Text,
  'onsetHistory' : IDL.Text,
  'chiefComplaint' : IDL.Text,
});
export const ObjectiveTest = IDL.Record({
  'muscleTesting' : IDL.Text,
  'rangeOfMotion' : IDL.Text,
  'gaitAssessment' : IDL.Text,
  'balanceAssessment' : IDL.Text,
  'neurologicalScreening' : IDL.Text,
  'cardiopulmonaryScreening' : IDL.Text,
});
export const Assessment = IDL.Record({
  'id' : AssessmentId,
  'clinicalScales' : IDL.Vec(ClinicalScale),
  'dateCreated' : IDL.Int,
  'patientId' : PatientId,
  'clinicianId' : ClinicianId,
  'redFlags' : IDL.Vec(IDL.Text),
  'subjectiveHistory' : SubjectiveHistory,
  'objectiveTest' : ObjectiveTest,
});
export const PatientProfile = IDL.Record({
  'id' : PatientId,
  'contactInfo' : IDL.Text,
  'activityGoals' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'medicalHistory' : IDL.Text,
  'gender' : IDL.Text,
  'lastName' : IDL.Text,
  'surgicalHistory' : IDL.Text,
  'firstName' : IDL.Text,
});
export const TreatmentPlan = IDL.Record({
  'id' : IDL.Text,
  'dateCreated' : IDL.Int,
  'patientId' : PatientId,
  'recommendations' : IDL.Vec(IDL.Text),
  'impairments' : IDL.Text,
  'clinicianId' : ClinicianId,
  'functionalLimitations' : IDL.Text,
  'diagnosis' : IDL.Text,
  'goals' : IDL.Text,
  'interventions' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AIPlanInput = IDL.Record({
  'age' : IDL.Nat,
  'painScore' : IDL.Nat,
  'primaryComplaint' : IDL.Text,
  'domain' : IDL.Text,
  'patientGoals' : IDL.Text,
  'functionalLimitations' : IDL.Text,
  'medicalHistory' : IDL.Text,
  'gender' : IDL.Text,
  'bodyPart' : IDL.Text,
  'symptomDuration' : IDL.Text,
});
export const AIPlanOutput = IDL.Record({
  'keyImpairments' : IDL.Text,
  'sessionDuration' : IDL.Text,
  'functionalProblems' : IDL.Text,
  'redFlagReferral' : IDL.Text,
  'contraindications' : IDL.Text,
  'exerciseList' : IDL.Vec(IDL.Text),
  'disclaimer' : IDL.Text,
  'longTermGoals' : IDL.Text,
  'frequency' : IDL.Text,
  'shortTermGoals' : IDL.Text,
  'precautions' : IDL.Vec(IDL.Text),
});
export const ImpressionId = IDL.Text;
export const ProvisionalPhysioImpression = IDL.Record({
  'id' : ImpressionId,
  'observedDeviations' : IDL.Vec(IDL.Text),
  'dateCreated' : IDL.Int,
  'generatedImpression' : IDL.Text,
  'functionalDifficulties' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'credentials' : IDL.Text,
  'specialization' : IDL.Text,
});
export const UserEntry = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
  'profile' : IDL.Opt(UserProfile),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Deviation = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'severity' : IDL.Nat,
});
export const PostureAssessmentReport = IDL.Record({
  'correctiveFocusAreas' : IDL.Vec(IDL.Text),
  'deviations' : IDL.Vec(Deviation),
  'effectsOnMovement' : IDL.Vec(IDL.Text),
  'disclaimer' : IDL.Text,
  'patientFriendlySummary' : IDL.Text,
  'explanations' : IDL.Vec(IDL.Text),
});
export const PostureAssessmentInput = IDL.Record({
  'landmarks' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'viewType' : IDL.Text,
  'alignmentData' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAssessment' : IDL.Func([Assessment], [AssessmentId], []),
  'addPatient' : IDL.Func([PatientProfile], [], []),
  'addTreatmentPlan' : IDL.Func([TreatmentPlan], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateClinicalScaleScore' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat)],
      [ClinicalScale],
      [],
    ),
  'generateAIPlan' : IDL.Func([AIPlanInput], [AIPlanOutput], []),
  'generateProvisionalPhysioImpression' : IDL.Func(
      [PatientId, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      [ProvisionalPhysioImpression],
      [],
    ),
  'getAllPatients' : IDL.Func([], [IDL.Vec(PatientProfile)], ['query']),
  'getAllProvisionalImpressions' : IDL.Func(
      [],
      [IDL.Vec(ProvisionalPhysioImpression)],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserEntry)], ['query']),
  'getAssessment' : IDL.Func([AssessmentId], [IDL.Opt(Assessment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClinicianDashboard' : IDL.Func(
      [],
      [
        IDL.Record({
          'aiPlanCount' : IDL.Nat,
          'treatmentPlanCount' : IDL.Nat,
          'patientCount' : IDL.Nat,
          'assessmentCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getPatient' : IDL.Func([PatientId], [IDL.Opt(PatientProfile)], ['query']),
  'getPatientAssessments' : IDL.Func(
      [PatientId],
      [IDL.Vec(Assessment)],
      ['query'],
    ),
  'getPatientTreatmentPlans' : IDL.Func(
      [PatientId],
      [IDL.Vec(TreatmentPlan)],
      ['query'],
    ),
  'getProvisionalImpressions' : IDL.Func(
      [PatientId],
      [IDL.Vec(ProvisionalPhysioImpression)],
      ['query'],
    ),
  'getTreatmentPlan' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TreatmentPlan)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'processPostureImage' : IDL.Func(
      [ExternalBlob],
      [PostureAssessmentReport],
      [],
    ),
  'removeUser' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPostureAssessment' : IDL.Func(
      [PostureAssessmentInput],
      [PostureAssessmentReport],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AssessmentId = IDL.Text;
  const ClinicalScale = IDL.Record({
    'responses' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'score' : IDL.Nat,
    'hjiquestions' : IDL.Text,
    'interpretation' : IDL.Text,
  });
  const PatientId = IDL.Text;
  const ClinicianId = IDL.Principal;
  const SubjectiveHistory = IDL.Record({
    'aggravatingFactors' : IDL.Text,
    'functionalLimitations' : IDL.Text,
    'relievingFactors' : IDL.Text,
    'onsetHistory' : IDL.Text,
    'chiefComplaint' : IDL.Text,
  });
  const ObjectiveTest = IDL.Record({
    'muscleTesting' : IDL.Text,
    'rangeOfMotion' : IDL.Text,
    'gaitAssessment' : IDL.Text,
    'balanceAssessment' : IDL.Text,
    'neurologicalScreening' : IDL.Text,
    'cardiopulmonaryScreening' : IDL.Text,
  });
  const Assessment = IDL.Record({
    'id' : AssessmentId,
    'clinicalScales' : IDL.Vec(ClinicalScale),
    'dateCreated' : IDL.Int,
    'patientId' : PatientId,
    'clinicianId' : ClinicianId,
    'redFlags' : IDL.Vec(IDL.Text),
    'subjectiveHistory' : SubjectiveHistory,
    'objectiveTest' : ObjectiveTest,
  });
  const PatientProfile = IDL.Record({
    'id' : PatientId,
    'contactInfo' : IDL.Text,
    'activityGoals' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'medicalHistory' : IDL.Text,
    'gender' : IDL.Text,
    'lastName' : IDL.Text,
    'surgicalHistory' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const TreatmentPlan = IDL.Record({
    'id' : IDL.Text,
    'dateCreated' : IDL.Int,
    'patientId' : PatientId,
    'recommendations' : IDL.Vec(IDL.Text),
    'impairments' : IDL.Text,
    'clinicianId' : ClinicianId,
    'functionalLimitations' : IDL.Text,
    'diagnosis' : IDL.Text,
    'goals' : IDL.Text,
    'interventions' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AIPlanInput = IDL.Record({
    'age' : IDL.Nat,
    'painScore' : IDL.Nat,
    'primaryComplaint' : IDL.Text,
    'domain' : IDL.Text,
    'patientGoals' : IDL.Text,
    'functionalLimitations' : IDL.Text,
    'medicalHistory' : IDL.Text,
    'gender' : IDL.Text,
    'bodyPart' : IDL.Text,
    'symptomDuration' : IDL.Text,
  });
  const AIPlanOutput = IDL.Record({
    'keyImpairments' : IDL.Text,
    'sessionDuration' : IDL.Text,
    'functionalProblems' : IDL.Text,
    'redFlagReferral' : IDL.Text,
    'contraindications' : IDL.Text,
    'exerciseList' : IDL.Vec(IDL.Text),
    'disclaimer' : IDL.Text,
    'longTermGoals' : IDL.Text,
    'frequency' : IDL.Text,
    'shortTermGoals' : IDL.Text,
    'precautions' : IDL.Vec(IDL.Text),
  });
  const ImpressionId = IDL.Text;
  const ProvisionalPhysioImpression = IDL.Record({
    'id' : ImpressionId,
    'observedDeviations' : IDL.Vec(IDL.Text),
    'dateCreated' : IDL.Int,
    'generatedImpression' : IDL.Text,
    'functionalDifficulties' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'credentials' : IDL.Text,
    'specialization' : IDL.Text,
  });
  const UserEntry = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
    'profile' : IDL.Opt(UserProfile),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Deviation = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'severity' : IDL.Nat,
  });
  const PostureAssessmentReport = IDL.Record({
    'correctiveFocusAreas' : IDL.Vec(IDL.Text),
    'deviations' : IDL.Vec(Deviation),
    'effectsOnMovement' : IDL.Vec(IDL.Text),
    'disclaimer' : IDL.Text,
    'patientFriendlySummary' : IDL.Text,
    'explanations' : IDL.Vec(IDL.Text),
  });
  const PostureAssessmentInput = IDL.Record({
    'landmarks' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'viewType' : IDL.Text,
    'alignmentData' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAssessment' : IDL.Func([Assessment], [AssessmentId], []),
    'addPatient' : IDL.Func([PatientProfile], [], []),
    'addTreatmentPlan' : IDL.Func([TreatmentPlan], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateClinicalScaleScore' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat)],
        [ClinicalScale],
        [],
      ),
    'generateAIPlan' : IDL.Func([AIPlanInput], [AIPlanOutput], []),
    'generateProvisionalPhysioImpression' : IDL.Func(
        [PatientId, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        [ProvisionalPhysioImpression],
        [],
      ),
    'getAllPatients' : IDL.Func([], [IDL.Vec(PatientProfile)], ['query']),
    'getAllProvisionalImpressions' : IDL.Func(
        [],
        [IDL.Vec(ProvisionalPhysioImpression)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserEntry)], ['query']),
    'getAssessment' : IDL.Func(
        [AssessmentId],
        [IDL.Opt(Assessment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClinicianDashboard' : IDL.Func(
        [],
        [
          IDL.Record({
            'aiPlanCount' : IDL.Nat,
            'treatmentPlanCount' : IDL.Nat,
            'patientCount' : IDL.Nat,
            'assessmentCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getPatient' : IDL.Func([PatientId], [IDL.Opt(PatientProfile)], ['query']),
    'getPatientAssessments' : IDL.Func(
        [PatientId],
        [IDL.Vec(Assessment)],
        ['query'],
      ),
    'getPatientTreatmentPlans' : IDL.Func(
        [PatientId],
        [IDL.Vec(TreatmentPlan)],
        ['query'],
      ),
    'getProvisionalImpressions' : IDL.Func(
        [PatientId],
        [IDL.Vec(ProvisionalPhysioImpression)],
        ['query'],
      ),
    'getTreatmentPlan' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TreatmentPlan)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'processPostureImage' : IDL.Func(
        [ExternalBlob],
        [PostureAssessmentReport],
        [],
      ),
    'removeUser' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPostureAssessment' : IDL.Func(
        [PostureAssessmentInput],
        [PostureAssessmentReport],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };